import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "../styles/Home.module.css";
import { getSession } from "next-auth/react";
import { sql } from "@vercel/postgres";

export async function getServerSideProps(context) {
  // Retrieve session to get the logged-in user
  const session = await getSession(context);

  // Get the user's ID from the session object (assuming session contains user_id)
  const userId = session.user.id;

  // Fetch data only for the logged-in user
  const logResult = await sql`SELECT * FROM logs WHERE user_id = ${userId}`;

  // Convert Date fields in `logs` table to JSON-serializable strings
  const logs = logResult.rows.map(row => ({
    ...row,
    date: row.date ? row.date.toISOString().split('T')[0] : null, // Only keep the date part
    start_time: row.start_time ? row.start_time.toISOString() : null,
    end_time: row.end_time ? row.end_time.toISOString() : null,
  }));

  return {
    props: {
      logs
    },
  };
}

export default function Home(props) {
  console.log(props)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div class="card m-2">
          <div class="card-body p-0">
            <h5 className="card-title m-0 p-3 d-flex justify-content-between" onClick={e=>AssetDateToggleExpand(Asset.initIndex, DateIndex)}>
              <span>Week</span>
            </h5>
          </div>
        </div>
        <div class="card m-2">
          <div class="card-body p-0">
            <h5 className="card-title m-0 p-3 d-flex justify-content-between" onClick={e=>AssetDateToggleExpand(Asset.initIndex, DateIndex)}>
              <span>Week</span>
            </h5>
          </div>
        </div>
      </main>
      <footer className={styles.footer}>
        
      </footer>
    </>
  );
}
